### PR TITLE
Adeyemi Esther

### PR DESCRIPTION
**Pull request by Xtarachiever**
This is Aeyemi's Esther first Assignment

### CODE REVIEW

**Comment by Xtarachiever** [comment]
Task 2

**Comment by ogheneovo12** [comment]
Please update your repo with the current repo version, and put your assignment in their respective week folder, follow PART TWO of the readme instruction.

**Comment by Xtarachiever** [comment]
Updated

**Comment by ogheneovo12** [comment]
Nice job

**Pull request merged**
